### ISSUE TITLE
Modules suggestion

### ISSUE THREAD

**Issue by parkjunmin** [securitybydesign/athenaeum#1]
https://www.criminalip.io/ - Criminal IP is a specialized Cyber Threat Intelligence (CTI) search engine that allows users to search for various security-related information such as malicious IP addresses, domains, banners, etc. It can be widely integrated

**Comment by renantmagalhaes** [comment]
Hey @parkjunmin thanks for the suggestion, by coincidence I was looking at other Threat intelligence tools last week, so its the perfect time to create this category :)
